# Generated by Django 5.1.1 on 2024-09-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
